### ISSUE TITLE
Please provide appstream common id

### ISSUE THREAD

**Issue by er-vin** [Joker2770/endlesssky-snap#1]
While working in porting some of the KDE applications on a system exposing only snap packages, I realized that Endless Sky couldn't be found by appstream id.

Indeed it looks like the snap packaging doesn't provide a common-id. So for instance if querying the search endpoint for Endless Sky common id like so:
```
curl -s "https://api.snapcraft.io/api/v1/snaps/search?common_id=io.github.endless_sky.endless_sky"|jq '._embedded|.["clickindex:package"]|.[]|.package_name'
```

We get no result. This is to be compared with for instance the VLC snap package which integrated appstream id in its data:
```
curl -s "https://api.snapcraft.io/api/v1/snaps/search?common_id=org.videolan.vlc"|jq '._embedded|.["clickindex:package"]|.[]|.package_name'
```

Could this be adjusted on the Endless Sky package? Endless Sky is advertised at a couple of place on the KDE side but since it's based on its appstream id, on a snap-only system this prevents from finding the application.

**Comment by Joker2770** [comment]
I have added common-id just now, and it looks OK when querying by the command you provided.

**Comment by er-vin** [comment]
Tested it and it seems to work properly. Thanks for handling this swiftly!
